version: "3.8"

name: meu-compose
services:
  redis:
    image: redis:alpine
    volumes:
    - type: bind
      source: /root/meu-compose/dados-redis
      target: /data
  web:
    build:
      context: /root/meu-compose
      dockerfile: Dockerfile
    ports:
    - mode: ingress
      target: 5000
      published: "5000"
